DELETE http://localhost:8080/events/3
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRla2Vkb3cyMjJAZ21haWwuY29tIiwiZXhwIjoxNzM2NDY4MDU2LCJ1c2VySUQiOjR9.JG3No71xXYtQM71V50e1VCbyhheiKMSt1JliH_6-Kzo